[tools]
# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "latest"
"aqua:hadolint/hadolint" = "latest"
