[program:sunshine]
command=/etc/sunshine/entrypoint.sh
environment=DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",DBUS_SYSTEM_BUS_ADDRESS="%(ENV_DBUS_SYSTEM_BUS_ADDRESS)s",PIPEWIRE_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",PULSE_RUNTIME_PATH="%(ENV_XDG_RUNTIME_DIR)s/pulse",PULSE_SERVER="unix:%(ENV_XDG_RUNTIME_DIR)s/pulse/native",SUNSHINE_USER="%(ENV_SUNSHINE_USER)s",SUNSHINE_PASSWORD="%(ENV_SUNSHINE_PASSWORD)s"
stdout_logfile=/tmp/sunshine.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=0
redirect_stderr=true
stopasgroup=true
stopsignal=INT
autostart=true
autorestart=true
priority=25
