---
name: Release
permissions: { contents: read }

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      select:
        description: "Select container to build"
        required: false
        default: ""
        type: string
  push:
    paths:
      - ".github/workflows/release.yaml"
      - "containers/**"

jobs:
  discover-containers:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.discover.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Find Containers
        id: discover
        uses: mirceanton/action-folder-matrix@e95694a82ad200463106846e8492b9a5bc9b5780 # v3.0.3
        with:
          path: ./containers
          changed-only: ${{ github.event_name != 'workflow_dispatch' }}
          filter: ${{ inputs.select }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: discover-containers
    runs-on: ubuntu-latest
    if: fromJson(needs.discover-containers.outputs.containers).directory[0] != null
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover-containers.outputs.containers) }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      
      - name: Log in to Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: mirceanton
          password: ${{ secrets.GHCR_RW_TOKEN }}

      - name: Build and push Docker image
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7.2.0
        with:
          push: ${{ (github.ref_name == 'main') || ( github.event_name == 'workflow_dispatch' && inputs.dry-run == false)}}
          source: ./containers/${{ matrix.directory }}
          files: ./docker-bake.hcl
          targets: default
        env:
          GIT_SHA: ${{ github.sha }}
